    <!-- / jquery [required] -->
    <script src="http://libs.useso.com/js/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <!-- / jquery ui -->
    <script src="http://libs.useso.com/js/jqueryui/1.10.2/jquery-ui.min.js" type="text/javascript"></script>
    <!-- / jquery mobile (for touch events) -->
    <script src="{$tpldir}/assets/js/jquery.mobile.custom.min.js" type="text/javascript"></script>
    <!-- / bootstrap [required] -->
    <script src="http://libs.useso.com/js/bootstrap/3.0.0/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- / theme file [required] -->
    <script src="{$tpldir}/assets/js/theme.min.js" type="text/javascript"></script>
    <!-- / START - page related files and scripts [optional] -->

    <!-- / END - page related files and scripts [optional] -->


