<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta content='text/html;charset=utf-8' http-equiv='content-type'>
    <meta content='' name='description'>
    <link href='{$tpldir}/assets/images/meta_icons/favicon.ico' rel='shortcut icon' type='image/x-icon'>
    <!-- / START - page related stylesheets [optional] -->
    <link href="{$tpldir}/assets/css/jquery_ui.min.css" media="all" rel="stylesheet" type="text/css" />
    <link href="{$tpldir}/assets/css/plugins.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / END - page related stylesheets [optional] -->
    <!-- / bootstrap [required] -->
    <link href="http://libs.useso.com/js/bootstrap/3.0.0/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <!-- / theme file [required] -->
    <link href="/static/default/assets/css/light-theme.min.css" media="all" id="color-settings-body-color" rel="stylesheet" type="text/css" />
    <!--[if lt IE 9]>
      <script src="http://libs.useso.com/js/html5shiv/3.6.2/html5shiv.min.js" type="text/javascript"></script>
      <script src="http://libs.useso.com/js/respond.js/1.3.0/respond.min.js" type="text/javascript"></script>
    <![endif]-->
    <link href="{$tpldir}/css/style.css" rel="stylesheet" type="text/css" />
  </head>
