{include file='before_body.phtml'}
<body class='contrast-fb without-footer'>
{include file='header.phtml'}
<div id='wrapper'>
{include file='sidebar.phtml' navigation='system'}
      <section id='content'>
        <div class='container'>
          <div class='row' id='content-wrapper'>
            <div class='col-xs-12'>

            </div>
          </div>
          {include file='footer.phtml'}
        </div>
      </section>
    </div>
</body>
{include file='after_body.phtml'}
</html>
