      <div id='main-nav-bg'></div>
      <nav id='main-nav'>
        <div class='navigation'>
          <ul class='nav nav-stacked'>
            <li class='active'>
              <a href='index.html'>
                <i class='icon-home'></i>
                <span>首页</span>
              </a>
            </li>
            <li class=''>
              <a class="dropdown-collapse in" href="#"><i class='icon-edit'></i>
                <span>系统设置</span>
                <i class='icon-angle-down angle-down'></i>
              </a>
              <ul class='nav nav-stacked in'>
                <li class=''>
                  <a href="{url('interface')}">
                    <i class='icon-caret-right'></i>
                    <span>接口设置</span>
                  </a>
                </li>
                <li class=''>
                  <a href="{url('interface/mainConfig')}">
                    <i class='icon-caret-right'></i>
                    <span>设置主配置</span>
                  </a>
                </li>
                <li class=''>
                  <a href="{url('liscence')}">
                    <i class='icon-caret-right'></i>
                    <span>产品授权</span>
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <a class='dropdown-collapse ' href='#'>
                <i class='icon-cog'></i>
                <span>业务设置</span>
                <i class='icon-angle-down angle-down'></i>
              </a>
              <ul class='nav nav-stacked'>
                <li class=''>
                  <a href="{url('business/get_business')}">
                    <i class='icon-caret-right'></i>
                    <span>全部业务</span>
                  </a>
                </li>
                <li class=''>
                  <a href="{url('business/getRule?do_id=0&range=2')}">
                    <i class='icon-caret-right'></i>
                    <span>全部规则</span>
                  </a>
                </li>
                <li class=''>
                  <a href="{url('business/add_business')}">
                    <i class='icon-caret-right'></i>
                    <span>添加业务</span>
                  </a>
                </li>
              </ul>
            </li>
            <li class=''>
              <a href="{url('valueadd/get_valueAdd')}">
                <i class='icon-star'></i>
                <span>增值业务</span>
              </a>
            </li>
            <li>
              <a class='dropdown-collapse ' href='#'>
                <i class='icon-cogs'></i>
                <span>设备状态</span>
                <i class='icon-angle-down angle-down'></i>
              </a>
              <ul class='nav nav-stacked'>
                <li class=''>
                  <a href=''>
                    <i class='icon-caret-right'></i>
                    <span>流量信息</span>
                  </a>
                </li>
                <li class=''>
                  <a href=''>
                    <i class='icon-caret-right'></i>
                    <span>CPU</span>
                  </a>
                </li>
                <li class=''>
                  <a href=''>
                    <i class='icon-caret-right'></i>
                    <span>内存</span>
                  </a>
                </li>
              </ul>
            </li>
            <li class=''>
              <a href="{url('statistics/get_statistics')}">
                <i class='icon-table'></i>
                <span>统计中心</span>
              </a>
            </li>
          </ul>
        </div>
      </nav>
