{include file='before_body.phtml'}
<body class='contrast-fb without-footer'>
  {include file='header.phtml'}
  <div id='wrapper'>
    {include file='sidebar.phtml'}
    <section id='content'>
      <div class='container'>
        <div class='row' id='content-wrapper'>
          <div class='col-xs-12'>
            <div class='page-header page-header-with-buttons'>
              <h1 class='pull-left'>
                <i class='icon-edit'></i>
                <span>添加授权信息</span>
              </h1>
            </div>
            <div class='row'>
              <div class='col-sm-12'>
                <form id="manage" method="post" action="{url('interface/addMainConfig')}" class="form form-horizontal" style="margin-bottom: 0;" accept-charset="UTF-8">
                  <input name="authenticity_token" type="hidden" >
                  {if isset($result) && $result}
                  <input type="hidden" name="main_id" value="{$result->main_id}">
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_dns_pkt_size'>max_dns_pkt_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_dns_pkt_size" id='max_dns_pkt_size' placeholder='max_dns_pkt_size' value="{$result->max_dns_pkt_size}" type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_http_pkt_size'>max_http_pkt_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_http_pkt_size" id='max_http_pkt_size' placeholder='max_http_pkt_size' value="{$result->max_http_pkt_size}"  type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_send_size'>max_send_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_send_size" id='max_send_size' placeholder='max_send_size' value="{$result->max_send_size}"  type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_send_size'>max_send_size_type：</label>
                    <div class='col-md-4'>
                      <select name="max_send_size_type" class='form-control' >
                        {if $result->max_send_size_type == 1}
                        <option value="1" selected>K</option>
                        {else}
                        <option value="1">K</option>
                        {/if}
                        {if $result->max_send_size_type == 2}
                        <option value="2" selected>M</option>
                        {else}
                        <option value="2">M</option>
                        {/if}
                      </select>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_log_len'>max_log_len：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_log_len" id='max_log_len' placeholder='max_log_len' value="{$result->max_log_len}"  type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='watermask'>watermask：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="watermask" id='watermask' placeholder='watermask' value="{$result->watermask}"  type='number'  min='0' max='1024'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='http_spoofers'>http_spoofers：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="http_spoofers" id='http_spoofers' placeholder='http_spoofers' value="{$result->http_spoofers}"  type='number' min='0' max='16'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='dns_spoofers'>dns_spoofers：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="dns_spoofers" id='dns_spoofers' placeholder='dns_spoofers' value="{$result->dns_spoofers}"  type='number' min='0'  max='16' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='method'>method：</label>
                    <div class='col-md-10'>
                      {if $result->http_method[0] == '1'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="1"  type='checkbox' checked>OPTIONS
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="1"  type='checkbox'>OPTIONS
                      </label>
                      {/if}
                      {if $result->http_method[1] == '2'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="2"  type='checkbox' checked>HEAD
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="2"  type='checkbox'>HEAD
                      </label>
                      {/if}
                      {if $result->http_method[2] == '3'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="3"  type='checkbox' checked>GET
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="3"  type='checkbox'>GET
                      </label>
                      {/if}
                      {if $result->http_method[3] == '4'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="4"  type='checkbox' checked>POST
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="4"  type='checkbox'>POST
                      </label>
                      {/if}
                      {if $result->http_method[4] == '5'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="5"  type='checkbox' checked>PUT
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="5"  type='checkbox'>PUT
                      </label>
                      {/if}
                      {if $result->http_method[5] == '6'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="6"  type='checkbox' checked>DELETE
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="6"  type='checkbox'>DELETE
                      </label>
                      {/if}
                      {if $result->http_method[6] == '7'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="7"  type='checkbox' checked>TRACE
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="7"  type='checkbox'>TRACE
                      </label>
                      {/if}
                      {if $result->http_method[7] == '8'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="8"  type='checkbox' checked>CONNECT
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="8"  type='checkbox'>CONNECT
                      </label>
                      {/if}
                      {if $result->http_method[8] == '9'}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="9"  type='checkbox' checked>PATCH
                      </label>
                      {else}
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="9"  type='checkbox'>PATCH
                      </label>
                      {/if}
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='dns_spoofers'>创建时间：</label>
                    <div class='col-md-4'>
                      {$result->created|date_format:"%Y-%m-%d %H:%M:%S"}
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='dns_spoofers'>更新时间：</label>
                    <div class='col-md-4'>
                      {$result->updated|date_format:"%Y-%m-%d %H:%M:%S"}
                    </div>
                  </div>
                  {else}
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_dns_pkt_size'>max_dns_pkt_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_dns_pkt_size" id='max_dns_pkt_size' placeholder='max_dns_pkt_size'  type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_http_pkt_size'>max_http_pkt_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_http_pkt_size" id='max_http_pkt_size' placeholder='max_http_pkt_size'  type='number'  min='0' >
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_send_size'>max_send_size：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_send_size" id='max_send_size' placeholder='max_send_size'  type='number'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_send_size_type'>max_send_size_type：</label>
                    <div class='col-md-4'>
                      <select name="max_send_size_type" class='form-control' >
                        <option value="1">K</option>
                        <option value="2">M</option>
                      </select>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='max_log_len'>max_log_len：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="max_log_len" id='max_log_len' placeholder='max_log_len'  type='number'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='watermask'>watermask：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="watermask" id='watermask' placeholder='watermask' type='number'  min='0' max='1024'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='http_spoofers'>http_spoofers：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="http_spoofers" id='http_spoofers' placeholder='http_spoofers' type='number'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='dns_spoofers'>dns_spoofers：</label>
                    <div class='col-md-4'>
                      <input class='form-control' name="dns_spoofers" id='dns_spoofers' placeholder='dns_spoofers'  type='number'>
                    </div>
                  </div>
                  <div class='form-group'>
                    <label class='col-md-2 control-label' for='method'>method：</label>
                    <div class='col-md-10'>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="1"  type='checkbox'>OPTIONS
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="2"  type='checkbox'>HEAD
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="3"  type='checkbox'>GET
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="4"  type='checkbox'>POST
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="5"  type='checkbox'>PUT
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="6"  type='checkbox'>DELETE
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="7"  type='checkbox'>TRACE
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="8"  type='checkbox'>CONNECT
                      </label>
                      <label class="checkbox-inline">
                        <input name="http_method[]" value="9"  type='checkbox'>PATCH
                      </label>
                    </div>
                  </div>
                  {/if}
                  <div class='form-actions form-actions-padding-sm'>
                    <div class='row'>
                      <div class='col-md-10 col-md-offset-2'>
                        <button class='btn btn-primary' type='submit'>
                          {if isset($result) && $result}
                          修改
                          {else}
                          添加
                          {/if}
                        </button>
                        <button class='btn' type='reset'>取消</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        {include file='footer.phtml'}
      </div>
    </section>
  </div>
</body>
{include file='after_body.phtml'}
</html>
