{include file='before_body.phtml'}
<body class='contrast-fb without-footer'>
  {include file='header.phtml'}
  <div id='wrapper'>
    {include file='sidebar.phtml'}
    <section id='content'>
      <div class='container'>
        <div class='row' id='content-wrapper'>
          <div class='col-xs-12'>
            <div class='page-header page-header-with-buttons'>
              <h1 class='pull-left'>
                <i class='icon-tags'></i>
                <span>详情页</span>
              </h1>
            </div>
            <div class='row'>
              <div class='col-sm-12'>
                <table class="data-table-column-filter table table-bordered table-striped dataTable" style="margin-bottom:0;" id="DataTables_Table_1" aria-describedby="DataTables_Table_1_info">
                  <thead>
                    <tr role="row">
                      <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 80px;">
                        data_num
                      </th>
                      <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 80px;">
                        head
                      </th>
                      <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 80px;">
                        body
                      </th>
                      <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_1" rowspan="1" colspan="1" style="width: 80px;">
                        创建时间
                      </th>
                    </tr>
                  </thead>
                  <tbody role="alert" aria-live="polite" aria-relevant="all">
                    {if isset($http_data) && $http_data}
                    {foreach $http_data as $value}
                    <tr>
                      <td class=" sorting_1">{$value['data_num']}</td>
                      <td class=" sorting_1">{$value['head']}</td>
                      <td class=" sorting_1">{$value['body']|escape}</td>
                      <td class=" sorting_1">{$value['created']|date_format:"%Y-%m-%d %H:%M:%S"}</td>
                    </tr>
                    {/foreach}
                    {/if}
                  </tbody>
                </table>
                <div class="col-md-14">
                  <div class="dataTables_paginate paging_bootstrap">
                    {html_pagination showinfo="1" page="$page" rows="$rows" count="$count" url="{url('business/getRule/%page%?do_id=0&data_num='|cat:{$data_num}|cat:'&range=3')}"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {include file='footer.phtml'}
      </div>
    </section>
  </div>
</body>
{include file='after_body.phtml'}
</html>
